CREATE DATABASE COACHX_ASSINGMENT;

USE COACHX_ASSINGMENT;

CREATE TABLE EMPLOYEE_DETAILS(
EMPID INT,
FULLNAME VARCHAR (50),
MANAGERID INT,
DATEOFJOINING DATE,
CITY VARCHAR (50)
);

INSERT INTO EMPLOYEE_DETAILS VALUES(121,'JOHN SNOW',321,'01/31/2019','TORONTO')
INSERT INTO EMPLOYEE_DETAILS VALUES(321,'WALTER WHITE',986,'01/30/2020','CALIFORNIA')
INSERT INTO EMPLOYEE_DETAILS VALUES(421,'KULDEEP RANA',876,'11/27/2021','NEW DELHI');

SELECT * FROM EMPLOYEE_DETAILS;

CREATE TABLE EMPLOYEE_SALARY(
EMPID INT,
PROJECT VARCHAR (50),
SALARY MONEY,
VARIABLE INT);

INSERT INTO EMPLOYEE_SALARY VALUES(121,'P1',8000,500)
INSERT INTO EMPLOYEE_SALARY VALUES(321,'P2',10000,1000)
INSERT INTO EMPLOYEE_SALARY VALUES(421,'P1',12000,0);

SELECT * FROM EMPLOYEE_DETAILS;
SELECT * FROM EMPLOYEE_SALARY;


--------------------- ASSINGMENT - 1 -------------------------

SELECT * FROM EMPLOYEE_SALARY
WHERE EMPID NOT IN
(SELECT EMPID FROM EMPLOYEE_DETAILS);

SELECT * FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
WHERE PROJECT NOT IN (PROJECT);

SELECT * FROM EMPLOYEE_DETAILS
WHERE YEAR(DATEOFJOINING) = 2020;

SELECT * FROM EMPLOYEE_DETAILS
FULL JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT COUNT(*)EMPID, PROJECT FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
GROUP BY PROJECT;

SELECT FULLNAME, SALARY FROM EMPLOYEE_DETAILS
FULL JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT EMPID, FULLNAME, MANAGERID, DATEOFJOINING, CITY, COUNT (*)FROM EMPLOYEE_DETAILS
GROUP BY EMPID, FULLNAME, MANAGERID, DATEOFJOINING, CITY
HAVING COUNT(*) > 1;

SELECT SALARY FROM EMPLOYEE_SALARY
WHERE SALARY <> (SELECT MAX (SALARY) FROM EMPLOYEE_SALARY);

SELECT MAX(SALARY) As Third_Highest_Salary FROM EMPLOYEE_SALARY 
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE_SALARY
WHERE SALARY NOT IN(SELECT MAX(SALARY) FROM EMPLOYEE_SALARY)) ;


--------------------- ASSINGMENT - 2 -------------------------


SELECT EMPID, FULLNAME, MANAGERID FROM EMPLOYEE_DETAILS
WHERE MANAGERID = 986;

SELECT DISTINCT (PROJECT) FROM EMPLOYEE_SALARY;

SELECT COUNT (EMPLOYEE_DETAILS.EMPID) AS PROJECT_EMPLOYEE FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
WHERE PROJECT = 'P1';

SELECT MAX(SALARY)AS MAX_SALARY, MIN(SALARY)AS MIN_SALARY, AVG(SALARY)AS AVG_SALARY 
FROM EMPLOYEE_SALARY;

SELECT (EMPLOYEE_DETAILS.EMPID), SALARY FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
WHERE SALARY BETWEEN 9000 AND 15000;

SELECT FULLNAME FROM EMPLOYEE_DETAILS
WHERE CITY LIKE 'TORONTO' AND MANAGERID = 321;

SELECT FULLNAME  FROM EMPLOYEE_DETAILS
WHERE CITY = 'CALIFORNIA' OR MANAGERID = 321 ;

SELECT FULLNAME FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
WHERE PROJECT NOT IN ('P1');

SELECT FULLNAME, SALARY, VARIABLE FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT FULLNAME FROM EMPLOYEE_DETAILS
WHERE FULLNAME LIKE '%HN';

--------------------- ASSINGMENT - 3 -------------------------

SELECT EMPLOYEE_DETAILS.EMPID AS EMP_DETAILS_ID FROM EMPLOYEE_DETAILS
LEFT JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT * FROM EMPLOYEE_SALARY
WHERE EMPID NOT IN
(SELECT EMPID FROM EMPLOYEE_DETAILS);

SELECT EMPLOYEE_DETAILS.EMPID AS EMP_DETAILS_ID, EMPLOYEE_SALARY.EMPID AS EMP_SAL_ID FROM EMPLOYEE_DETAILS
LEFT JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT EMPID, MANAGERID FROM EMPLOYEE_DETAILS;

SELECT SUBSTRING(FULLNAME, 1, CHARINDEX(' ', FULLNAME) - 1) AS Firstname     
FROM EMPLOYEE_DETAILS;

SELECT UPPER(FULLNAME) AS FULLNAME, LOWER(CITY) AS CITY FROM EMPLOYEE_DETAILS;

--------------------- ASSINGMENT - 4 -------------------------

SELECT COUNT(FULLNAME) AS TOTAL_OCCURRENCE_N FROM EMPLOYEE_DETAILS
WHERE FULLNAME LIKE '%N%';

SELECT * FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
WHERE PROJECT NOT IN (PROJECT);

SELECT FULLNAME, SALARY FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
WHERE SALARY >=5000 AND SALARY <=10000;

SELECT GETDATE();

SELECT * FROM EMPLOYEE_DETAILS
WHERE YEAR(DATEOFJOINING) = 2020;

SELECT * FROM EMPLOYEE_DETAILS
FULL JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT COUNT(*)EMPID, PROJECT FROM EMPLOYEE_DETAILS
JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID
GROUP BY PROJECT
ORDER BY COUNT (PROJECT) DESC;

SELECT FULLNAME, SALARY FROM EMPLOYEE_DETAILS
FULL JOIN EMPLOYEE_SALARY
ON EMPLOYEE_DETAILS.EMPID = EMPLOYEE_SALARY.EMPID;

SELECT
  FIRSTNAME, LASTNAME, CITY, COURSENAME
FROM STUDENT
JOIN STUDENT_COURSE
  ON STUDENT.ID = STUDENT_COURSE.STUDENT.ID
JOIN COURSE
  ON COURSE.ID = STUDENT_COURSE.STUDENT.ID;

--------------------- ADVANCED ASSINGMENT --------------------------

CREATE TABLE EMPLOYEEINFO (
EMPID INT,
EMPFNAME VARCHAR(50),
EMPLNAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
PROJECT VARCHAR(50),
ADDRESS VARCHAR(50),
DOB DATE,
GENDER VARCHAR(10));

INSERT INTO EMPLOYEEINFO VALUES(1,'Sanjay','Mehra','HR','P1','Hyderabad(HYD)','01/12/1976','M')
INSERT INTO EMPLOYEEINFO VALUES(2,'Ananya','Mishra','Admin','P2','Delhi(DEL)','02/05/1968','F')
INSERT INTO EMPLOYEEINFO VALUES(3,'Rohan','Diwan','Account','P3','Mumbai(BOM)','01/01/1980','M')
INSERT INTO EMPLOYEEINFO VALUES(4,'Sonia','Kulkarni','HR','P1','Hyderabad(HYD)','02/05/1992','F')
INSERT INTO EMPLOYEEINFO VALUES(5,'Ankit','Kapoor','Admin','P2','Delhi(DEL)','03/07/1994','M')

SELECT * FROM EMPLOYEEINFO;

CREATE TABLE EMPLOYEE_POSITION (
EMPID INT,
EMPPOSITION VARCHAR(50),
DOJ DATE,
SALARY MONEY);

INSERT INTO EMPLOYEE_POSITION VALUES(1,'Manager','01/05/2022',500000)
INSERT INTO EMPLOYEE_POSITION VALUES(2,'Executive','02/05/2022',75000)
INSERT INTO EMPLOYEE_POSITION VALUES(3,'Manager','01/05/2022',90000)
INSERT INTO EMPLOYEE_POSITION VALUES(2,'Lead','02/05/2022',85000)
INSERT INTO EMPLOYEE_POSITION VALUES(1,'Executive','01/05/2022',300000)

SELECT * FROM EMPLOYEE_POSITION;

SELECT UPPER(EMPFNAME) AS ALIAS FROM EMPLOYEEINFO;

SELECT COUNT(EMPID) AS HR_DEPT_EMP FROM EMPLOYEEINFO
WHERE DEPARTMENT = 'HR';

SELECT GETDATE();

SELECT LEFT(EMPLNAME,4) AS FIRST_FOUR_CHAR FROM EMPLOYEEINFO;

SELECT SUBSTRING (ADDRESS, '(',1) AS PlaceName FROM EMPLOYEEINFO;
    
SELECT EMPLOYEEINFO.EMPID, EMPFNAME, EMPLNAME, SALARY FROM EMPLOYEEINFO
FULL JOIN EMPLOYEE_POSITION
ON EMPLOYEEINFO.EMPID = EMPLOYEE_POSITION.EMPID
WHERE SALARY BETWEEN 50000 AND 100000;

SELECT EMPFNAME FROM EMPLOYEEINFO
WHERE EMPFNAME LIKE 'S%';

SELECT TOP 3 * FROM EMPLOYEEINFO;

SELECT CONCAT(EMPFNAME,' ',EMPLNAME) AS EMP_FULL_NAME FROM EMPLOYEEINFO;

SELECT COUNT(EMPID) FROM EMPLOYEEINFO
WHERE DOB BETWEEN '02/05/1970' AND '31/12/1975'
GROUP BY GENDER;

SELECT COUNT (EMPID), GENDER AS NumberOfEmployees FROM EMPLOYEEINFO
WHERE DOB BETWEEN '1970-05-02' AND '1975-12-31'
GROUP BY Gender;

SELECT * FROM EMPLOYEEINFO
ORDER BY EMPLNAME DESC, DEPARTMENT ASC;

SELECT EMPLNAME FROM EMPLOYEEINFO
WHERE EMPLNAME LIKE '____A';

SELECT * FROM EMPLOYEEINFO
WHERE EMPFNAME NOT IN ('SANJAY','SONIA');

SELECT * FROM EMPLOYEEINFO
WHERE ADDRESS = 'DELHI(DEL)';

SELECT * FROM EMPLOYEEINFO
JOIN EMPLOYEE_POSITION
ON EMPLOYEEINFO.EMPID = EMPLOYEE_POSITION.EMPID
WHERE EMPPOSITION = 'MANAGER';
 

SELECT DEPARTMENT, COUNT(*) AS EMP_COUNT FROM EMPLOYEEINFO
GROUP BY DEPARTMENT
ORDER BY EMP_COUNT ASC;

SELECT * FROM EMPLOYEEINFO
INNER JOIN EMPLOYEE_POSITION
ON EMPLOYEEINFO.EMPID = EMPLOYEE_POSITION.EMPID
WHERE DOJ IN (DOJ);

SELECT MAX(SALARY) AS MAXIMUM_SALARY, MIN(SALARY) AS MINIMUM_SALARY FROM EMPLOYEE_POSITION;

SELECT MAX(SALARY) FROM EMPLOYEE_POSITION
WHERE SALARY <> (SELECT MAX(SALARY) FROM EMPLOYEE_POSITION
WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM EMPLOYEE_POSITION));

SELECT * FROM EMPLOYEEINFO
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEEINFO
GROUP BY DEPARTMENT
HAVING COUNT(*) > 1);

SELECT * FROM EMPLOYEEINFO
WHERE EMPID > (SELECT COUNT(*) FROM EMPLOYEEINFO) - 3;

SELECT MAX(SALARY) As Third_Highest_Salary FROM EMPLOYEE_POSITION
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE_POSITION
WHERE SALARY NOT IN(SELECT MAX(SALARY) FROM EMPLOYEE_POSITION)) ;

SELECT DEPARTMENT FROM EMPLOYEEINFO
GROUP BY DEPARTMENT
HAVING COUNT(*) < 2;

SELECT EMPPOSITION, SALARY FROM EMPLOYEE_POSITION;

SELECT TOP 50 PERCENT * FROM EMPLOYEEINFO;

--------------------------------------------------------------------