CREATE DATABASE ORDER_STORE_DATA;

USE ORDER_STORE_DATA;

CREATE TABLE ORDER_TABLE(
ORDER_ID INT NOT NULL,
ORDER_DATE DATE,
REGION VARCHAR(50),
REP VARCHAR(50),
ORDER_ITEM VARCHAR(50),
UNITS INT,
UNIT_COST FLOAT(2),
TOTAL_PRICE FLOAT(2));

INSERT INTO ORDER_TABLE VALUES(1,'06-01-2021','East','Aruna','Pencil',95,1.99,189.05)
INSERT INTO ORDER_TABLE VALUES(2,'01-23-2021','Central','kivell','Eraser',50,19.99,999.50)
INSERT INTO ORDER_TABLE VALUES(3,'02-09-2021','Central','Ganesh',null,36,04.99,179.64)
INSERT INTO ORDER_TABLE VALUES(4,'02-26-2021','Central','Payal',null,27,19.99,539.73)
INSERT INTO ORDER_TABLE VALUES(5,'03-15-2021','West','Sorvino',null,56,02.99,167.44)
INSERT INTO ORDER_TABLE VALUES(6,'04-01-2021','East','Hitesh','Pencil',60,04.99,299.40)
INSERT INTO ORDER_TABLE VALUES(7,'04-18-2021','Central','Akshita',null,75,01.99,149.25)
INSERT INTO ORDER_TABLE VALUES(8,'05-05-2021','Central','Ruchika','Books',90,04.99,449.10)
INSERT INTO ORDER_TABLE VALUES(9,'05-22-2021','West','Surbhi',null,32,01.99,63.68)
INSERT INTO ORDER_TABLE VALUES(10,'06-08-2021','East','Jones','Suitcase',60,08.99,539.40);

SELECT * FROM ORDER_TABLE;

ALTER TABLE ORDER_TABLE   
ADD CONSTRAINT PK_ORDER_ID PRIMARY KEY (ORDER_ID);

CREATE TABLE STORE_TABLE(
STORE_ID INT,
STORE_TYPE VARCHAR(50),
ASSORTMENT INT,
COMPETITION_DISTANCE INT,
MONTH INT,
YEAR INT,
PROMOINTERVAL VARCHAR(50));

INSERT INTO STORE_TABLE VALUES(1,'C',17,1270,9,2008,'Jan')
INSERT INTO STORE_TABLE VALUES(2,'A',36,570,11,2007,'Feb')
INSERT INTO STORE_TABLE VALUES(3,'A',42,14130,12,2006,'Mar')
INSERT INTO STORE_TABLE VALUES(4,'C',35,620,9,2009,' ')
INSERT INTO STORE_TABLE VALUES(5,'A',42,29910,4,2015,'May')
INSERT INTO STORE_TABLE VALUES(6,'A',22,310,12,2013,'June')
INSERT INTO STORE_TABLE VALUES(7,'A',49,24000,4,2013,' ')
INSERT INTO STORE_TABLE VALUES(8,'A',42,7520,10,2014,'Aug')
INSERT INTO STORE_TABLE VALUES(9,'A',47,2030,8,2000,' ')
INSERT INTO STORE_TABLE VALUES(10,'A',20,3160,9,2009,'Oct');

SELECT * FROM STORE_TABLE;


ALTER TABLE STORE_TABLE
ADD STORE_NAMES VARCHAR (50);

UPDATE STORE_TABLE
SET STORE_NAMES = 'Car'
WHERE STORE_ID = 1;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Bikes'
WHERE STORE_ID = 2;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Hardware'
WHERE STORE_ID = 3;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Electrics'
WHERE STORE_ID = 4;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Fiber'
WHERE STORE_ID = 5;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Elastics'
WHERE STORE_ID = 6;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Books'
WHERE STORE_ID = 7;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Shoes'
WHERE STORE_ID = 8;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Clothes'
WHERE STORE_ID = 9;

UPDATE STORE_TABLE
SET STORE_NAMES = 'Scarps'
WHERE STORE_ID = 10;

ALTER TABLE STORE_TABLE
ADD CONSTRAINT FK_STORE_ID 
FOREIGN KEY (STORE_ID) REFERENCES ORDER_TABLE (ORDER_ID);

UPDATE ORDER_TABLE
SET ORDER_ITEM = 'Compass'
WHERE ORDER_ID = 3;

UPDATE ORDER_TABLE
SET ORDER_ITEM = 'Torch'
WHERE ORDER_ID = 4;

UPDATE ORDER_TABLE
SET ORDER_ITEM = 'Phone'
WHERE ORDER_ID = 5;

UPDATE ORDER_TABLE
SET ORDER_ITEM = 'Laptop'
WHERE ORDER_ID = 7;

UPDATE ORDER_TABLE
SET ORDER_ITEM = 'Box'
WHERE ORDER_ID = 9;

UPDATE STORE_TABLE
SET PROMOINTERVAL = 'Apr'
WHERE STORE_ID = 4;

UPDATE STORE_TABLE
SET PROMOINTERVAL = 'Jul'
WHERE STORE_ID = 7;

UPDATE STORE_TABLE
SET PROMOINTERVAL = 'Sept'
WHERE STORE_ID = 9;


SELECT UNIT_COST FROM ORDER_TABLE
ORDER BY UNIT_COST DESC;

SELECT TOTAL_PRICE FROM ORDER_TABLE
ORDER BY TOTAL_PRICE ASC;

EXEC sp_rename 'STORE_TABLE.ASSORTMENT','STORE_NOS','COLUMN';

EXEC sp_rename 'ORDER_TABLE.ORDER_ITEM','ITEM_NAME','COLUMN';

EXEC sp_rename 'ORDER_TABLE.REP','CUSTOMERS_NAME','COLUMN';

SELECT REGION, COUNT(*) AS CUST_NAME FROM ORDER_TABLE
GROUP BY REGION;

SELECT SUM(TOTAL_PRICE)AS TOTAL_OF_PRICE, SUM(UNIT_COST)AS TOTAL_UNIT_COST
FROM ORDER_TABLE;

SELECT ORDER_DATE, UNIT_COST, STORE_TYPE, YEAR FROM ORDER_TABLE 
JOIN STORE_TABLE
ON ORDER_TABLE.ORDER_ID = STORE_TABLE.STORE_ID;

SELECT ORDER_ID, ITEM_NAME, REGION FROM ORDER_TABLE
WHERE ORDER_ID IN (4,5,6,9);

SELECT YEAR, CD FROM STORE_TABLE
WHERE CD IN(29910,310,3160);

SELECT ITEM_NAME FROM ORDER_TABLE   
WHERE TOTAL_PRICE >= 200 AND TOTAL_PRICE <= 400;

EXEC sp_rename 'STORE_TABLE.COMPETITION_DISTANCE','CD','COLUMN';

SELECT SUM(CD)AS TOTAL_CD FROM STORE_TABLE;

SELECT COUNT(STORE_TYPE)AS COUNT_OF_STORE_TYPE, COUNT(CD)AS COUNT_OF_CD FROM STORE_TABLE;

SELECT * FROM ORDER_TABLE
CROSS JOIN STORE_TABLE;

-----------------------------------------

DROP TABLE ORDER_TABLE;

DROP TABLE STORE_TABLE;

-----------------------------------------




 

